DROP TABLE IF EXISTS LECTURERS;
CREATE TABLE LECTURERS (ID INTEGER PRIMARY KEY AUTOINCREMENT, POST_ID TEXT, TITLE TEXT, MP3 TEXT, CLASSNAME TEXT, CUSTOM TEXT, TYPE TEXT, CPOST_ID TEXT, TIME TEXT, IMAGE_URL TEXT);

